FROM python:3.11

# Copier les fichiers de mon app
COPY requirements.txt .
COPY api_stat.py .
COPY connect.py .
COPY statistics.py .
COPY statistics2.py .
COPY statistics3.py .
COPY statistics4.py .
COPY statistics5.py .

# Installer les dépendances
RUN pip install -r requirements.txt

# Installer Gunicorn
RUN pip install gunicorn

# Lancer Gunicorn avec  application Flask
CMD ["gunicorn", "-b", "0.0.0.0:8000", "api_stat:app"]


