FROM python:3.9-slim

# Copier les fichiers de mon app
COPY requirement.txt .
COPY api_stat.py .

# Installer les dépendances
RUN pip install -r requirements.txt

# Installer Gunicorn
RUN pip install gunicorn

# Lancer Gunicorn avec  application Flask
CMD ["gunicorn", "-b", "0.0.0.0:8000", "api_stat:app"]


